CREATE USER PEN IDENTIFIED BY opensourcedPassword;
GRANT UNLIMITED TABLESPACE TO PEN;
ALTER SESSION SET CURRENT_SCHEMA = PEN;


CREATE TABLE PEN.T_AVVIKSINFORMASJON (
    AVVIKSINFORMASJON_ID NUMBER,
    APPLIKASJON          VARCHAR2(50 CHAR)
);

INSERT INTO PEN.T_AVVIKSINFORMASJON (AVVIKSINFORMASJON_ID, APPLIKASJON) VALUES(1, 'PSAK');
INSERT INTO PEN.T_AVVIKSINFORMASJON (AVVIKSINFORMASJON_ID, APPLIKASJON) VALUES(2, 'PSAK');
INSERT INTO PEN.T_AVVIKSINFORMASJON (AVVIKSINFORMASJON_ID, APPLIKASJON) VALUES(3, 'PSELV');


CREATE TABLE PEN.T_AVVIKSTILFELLE (
    AVVIKSTILFELLE_ID NUMBER,
    AVVIKSGRUPPE_ID NUMBER
);

INSERT INTO PEN.T_AVVIKSTILFELLE (AVVIKSTILFELLE_ID, AVVIKSGRUPPE_ID) VALUES(1, 1);
INSERT INTO PEN.T_AVVIKSTILFELLE (AVVIKSTILFELLE_ID, AVVIKSGRUPPE_ID) VALUES(2, 2);
INSERT INTO PEN.T_AVVIKSTILFELLE (AVVIKSTILFELLE_ID, AVVIKSGRUPPE_ID) VALUES(3, 3);


CREATE TABLE PEN.T_AVVIKSGRUPPE (
    AVVIKSGRUPPE_ID NUMBER,
    AVVIKSINFORMASJON_ID NUMBER
);

INSERT INTO PEN.T_AVVIKSGRUPPE (AVVIKSGRUPPE_ID, AVVIKSINFORMASJON_ID) VALUES(1, 1);
INSERT INTO PEN.T_AVVIKSGRUPPE (AVVIKSGRUPPE_ID, AVVIKSINFORMASJON_ID) VALUES(2, 2);
INSERT INTO PEN.T_AVVIKSGRUPPE (AVVIKSGRUPPE_ID, AVVIKSINFORMASJON_ID) VALUES(3, 3);