name: Prod deployment
on:
  push:
    branches:
      - master
jobs:
  deploy-to-prod:
    name: Build, push and deploy to prod-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build code
        run: ./gradlew test build --info
      - name: Create Docker tag
        env:
          NAME: pensjon-saksbehandling-feilmetrikker
        run: |
          echo "IMAGE=docker.pkg.github.com/"$GITHUB_REPOSITORY"/"$NAME"" >> $GITHUB_ENV
          echo "VERSION=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker build -t ${IMAGE}:${VERSION} .
        env:
          IMAGE: ${{ env.IMAGE }}
          VERSION: ${{ env.VERSION }}
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - name: Push Docker image
        run: docker push ${IMAGE}:${VERSION}
        env:
          IMAGE: ${{ env.IMAGE }}
          VERSION: ${{ env.VERSION }}
      - name: deploy to prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: prod-fss
          RESOURCE: nais-prod.yaml
          IMAGE: ${{ env.IMAGE }}:${{ env.VERSION }}
